<?xml version="1.0" encoding="utf-8"?><Database Name="OldDB" Class="OldContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=laptop-a88v89ut;Initial Catalog=OldDB;Integrated Security=True;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="OldDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Old" Member="Olds">
    <Type Name="Old">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="yearOfBirth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Seniority" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>